//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Forms
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Course.
    /// </summary>
    // *** Start programmer edit section *** (Course CustomAttributes)

    // *** End programmer edit section *** (Course CustomAttributes)
    [AutoAltered()]
    [Caption("Name")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CourseE", new string[] {
            "Name as \'Name\'",
            "Registration as \'Registration\'",
            "Registration.CourseType as \'Course type\'"}, Hidden=new string[] {
            "Registration.CourseType"})]
    [MasterViewDefineAttribute("CourseE", "Registration", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "CourseType")]
    [View("CourseL", new string[] {
            "Name as \'Name\'",
            "Registration.CourseType as \'Course type\'"})]
    public class Course : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Forms.Registration fRegistration;
        
        // *** Start programmer edit section *** (Course CustomMembers)

        // *** End programmer edit section *** (Course CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Course.Name CustomAttributes)

        // *** End programmer edit section *** (Course.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Course.Name Get start)

                // *** End programmer edit section *** (Course.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Course.Name Get end)

                // *** End programmer edit section *** (Course.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Course.Name Set start)

                // *** End programmer edit section *** (Course.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Course.Name Set end)

                // *** End programmer edit section *** (Course.Name Set end)
            }
        }
        
        /// <summary>
        /// Course.
        /// </summary>
        // *** Start programmer edit section *** (Course.Registration CustomAttributes)

        // *** End programmer edit section *** (Course.Registration CustomAttributes)
        [NotNull()]
        public virtual IIS.Forms.Registration Registration
        {
            get
            {
                // *** Start programmer edit section *** (Course.Registration Get start)

                // *** End programmer edit section *** (Course.Registration Get start)
                IIS.Forms.Registration result = this.fRegistration;
                // *** Start programmer edit section *** (Course.Registration Get end)

                // *** End programmer edit section *** (Course.Registration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Course.Registration Set start)

                // *** End programmer edit section *** (Course.Registration Set start)
                this.fRegistration = value;
                // *** Start programmer edit section *** (Course.Registration Set end)

                // *** End programmer edit section *** (Course.Registration Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CourseE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CourseE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CourseE", typeof(IIS.Forms.Course));
                }
            }
            
            /// <summary>
            /// "CourseL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CourseL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CourseL", typeof(IIS.Forms.Course));
                }
            }
        }
    }
}
