//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Forms
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Registration.
    /// </summary>
    // *** Start programmer edit section *** (Registration CustomAttributes)

    // *** End programmer edit section *** (Registration CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("RegistrationE", new string[] {
            "CourseType as \'Course type\'",
            "DateOfRegister as \'Date of register\'",
            "Course",
            "Student"})]
    [MasterViewDefineAttribute("RegistrationE", "Course", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("RegistrationE", "Student", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("RegistrationL", new string[] {
            "CourseType as \'Course type\'",
            "DateOfRegister as \'Date of register\'",
            "Course.Name as \'Course\'",
            "Student.Name as \'Student\'"})]
    public class Registration : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Forms.tCourse fCourseType;
        
        private System.DateTime fDateOfRegister;
        
        private IIS.Forms.Course fCourse;
        
        private IIS.Forms.Student fStudent;
        
        // *** Start programmer edit section *** (Registration CustomMembers)

        // *** End programmer edit section *** (Registration CustomMembers)

        
        /// <summary>
        /// CourseType.
        /// </summary>
        // *** Start programmer edit section *** (Registration.CourseType CustomAttributes)

        // *** End programmer edit section *** (Registration.CourseType CustomAttributes)
        public virtual IIS.Forms.tCourse CourseType
        {
            get
            {
                // *** Start programmer edit section *** (Registration.CourseType Get start)

                // *** End programmer edit section *** (Registration.CourseType Get start)
                IIS.Forms.tCourse result = this.fCourseType;
                // *** Start programmer edit section *** (Registration.CourseType Get end)

                // *** End programmer edit section *** (Registration.CourseType Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.CourseType Set start)

                // *** End programmer edit section *** (Registration.CourseType Set start)
                this.fCourseType = value;
                // *** Start programmer edit section *** (Registration.CourseType Set end)

                // *** End programmer edit section *** (Registration.CourseType Set end)
            }
        }
        
        /// <summary>
        /// DateOfRegister.
        /// </summary>
        // *** Start programmer edit section *** (Registration.DateOfRegister CustomAttributes)

        // *** End programmer edit section *** (Registration.DateOfRegister CustomAttributes)
        public virtual System.DateTime DateOfRegister
        {
            get
            {
                // *** Start programmer edit section *** (Registration.DateOfRegister Get start)

                // *** End programmer edit section *** (Registration.DateOfRegister Get start)
                System.DateTime result = this.fDateOfRegister;
                // *** Start programmer edit section *** (Registration.DateOfRegister Get end)

                // *** End programmer edit section *** (Registration.DateOfRegister Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.DateOfRegister Set start)

                // *** End programmer edit section *** (Registration.DateOfRegister Set start)
                this.fDateOfRegister = value;
                // *** Start programmer edit section *** (Registration.DateOfRegister Set end)

                // *** End programmer edit section *** (Registration.DateOfRegister Set end)
            }
        }
        
        /// <summary>
        /// Registration.
        /// </summary>
        // *** Start programmer edit section *** (Registration.Course CustomAttributes)

        // *** End programmer edit section *** (Registration.Course CustomAttributes)
        [NotNull()]
        public virtual IIS.Forms.Course Course
        {
            get
            {
                // *** Start programmer edit section *** (Registration.Course Get start)

                // *** End programmer edit section *** (Registration.Course Get start)
                IIS.Forms.Course result = this.fCourse;
                // *** Start programmer edit section *** (Registration.Course Get end)

                // *** End programmer edit section *** (Registration.Course Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.Course Set start)

                // *** End programmer edit section *** (Registration.Course Set start)
                this.fCourse = value;
                // *** Start programmer edit section *** (Registration.Course Set end)

                // *** End programmer edit section *** (Registration.Course Set end)
            }
        }
        
        /// <summary>
        /// Registration.
        /// </summary>
        // *** Start programmer edit section *** (Registration.Student CustomAttributes)

        // *** End programmer edit section *** (Registration.Student CustomAttributes)
        [NotNull()]
        public virtual IIS.Forms.Student Student
        {
            get
            {
                // *** Start programmer edit section *** (Registration.Student Get start)

                // *** End programmer edit section *** (Registration.Student Get start)
                IIS.Forms.Student result = this.fStudent;
                // *** Start programmer edit section *** (Registration.Student Get end)

                // *** End programmer edit section *** (Registration.Student Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Registration.Student Set start)

                // *** End programmer edit section *** (Registration.Student Set start)
                this.fStudent = value;
                // *** Start programmer edit section *** (Registration.Student Set end)

                // *** End programmer edit section *** (Registration.Student Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "RegistrationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegistrationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegistrationE", typeof(IIS.Forms.Registration));
                }
            }
            
            /// <summary>
            /// "RegistrationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View RegistrationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("RegistrationL", typeof(IIS.Forms.Registration));
                }
            }
        }
    }
}
