//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Forms
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Courses.
    /// </summary>
    // *** Start programmer edit section *** (tCourse CustomAttributes)

    // *** End programmer edit section *** (tCourse CustomAttributes)
    public enum tCourse
    {
        
        // *** Start programmer edit section *** (tCourse.Programming CustomAttributes)

        // *** End programmer edit section *** (tCourse.Programming CustomAttributes)
        [Caption("Advanced Python")]
        Programming,
        
        // *** Start programmer edit section *** (tCourse.Mathematics CustomAttributes)

        // *** End programmer edit section *** (tCourse.Mathematics CustomAttributes)
        [Caption("Elective Maths")]
        Mathematics,
        
        // *** Start programmer edit section *** (tCourse.Economics CustomAttributes)

        // *** End programmer edit section *** (tCourse.Economics CustomAttributes)
        [Caption("Economics")]
        Economics,
        
        // *** Start programmer edit section *** (tCourse.Project CustomAttributes)

        // *** End programmer edit section *** (tCourse.Project CustomAttributes)
        [Caption("Project Management")]
        Project,
    }
}
